Add support and documentation for R: prefix (JSON curly brackets supp…
pytest-dev/pytest-env pull request #5
Opened 2022-10-21 14:35 UTC by Elijas

…ort)

2022-10-21 14:39 UTC, Elijas commented on src/pytest_env/plugin.py
> +        rkey = key.split("R:")
Using the same code conventions and patterns as the rest of the file.

2022-10-21 23:03 UTC, gaborbernat requested changes
Needs test.

2022-10-22 19:37 UTC, Elijas commented
@gaborbernat Try now.

2022-10-22 19:39 UTC, gaborbernat commented
Can you please rebase on main?

2022-10-22 19:39 UTC, gaborbernat commented on tests/example.py
> +class TestSimpleBehavior:
please no classes, methods are enough

2022-10-22 19:40 UTC, gaborbernat commented on tests/example_pytest.ini
> +[pytest]
Let's not conflate multiple tests into one, and please move the conf closer to the test as shown in the current test example.

2022-10-22 19:41 UTC, gaborbernat commented on src/pytest_env/plugin.py
> +_ALLOWED_FLAGS = (_DEFAULT_FLAG, _RAW_FLAG)
Add final type annotations to these

2022-10-22 21:37 UTC, gaborbernat commented
Please actually rebase.

2022-10-22 21:58 UTC, closed without merging

2022-10-22 22:24 UTC, Elijas commented
Development moved to #8

2022-10-23 02:11 UTC, gaborbernat commented on .pre-commit-config.yaml
> +        - flake8-unused-arguments==0.0.12
Why do these changes show up here, did you rebase?

2022-10-23 02:12 UTC, gaborbernat commented on src/pytest_env/plugin.py
> +_DEFAULT_FLAG: Final = 'D'
Needs type arg in []